version: 2.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
          pkg-manager: npm
      - run:
          command: npm run build && npm run ext
          name: Run build
      - test:
          command: npm run test
          name: Run tests
      - sonarcloud/scan

orbs:
  node: circleci/node@5.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
